name: n1 docker OpenWrt CI
on:
#  schedule:
#    - cron:  0 7 * * 6
#  push:
#    branches:
#      - master
    paths:
      - '.config.n1.docker'
      - 'n1/**'
  #watch:
  #  types: [started]

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout - clone repository
      uses: actions/checkout@v1

    - name: Install - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip pigz

    - name: Download - openwrt source download
      run: |
        git clone -b dev-lean-lede https://github.com/Lienol/openwrt
        
    - name: Update - openwrt source update and install 
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Config - n1 docker openwrt build config
      run: |
        [ -e n1/diy.sh ] && mv n1/diy.sh openwrt/diy.sh
        cp .config.n1.docker openwrt/.config
        cd openwrt
        [ -e diy.sh ] && chmod +x diy.sh && bash diy.sh
        make defconfig
    - name: Download - openwrt build dependencies
      run: |
        cd openwrt
        make download -j8
    - name: Build - make openwrt source
      run: |
        cd openwrt
        make -j$(nproc)
    - name: Docker file - copy Docker file
      run: |
        cp openwrt/bin/targets/armvirt/64/openwrt-armvirt-64-default-rootfs.tar.gz n1
    - name: Image - build docker image
      run: |
        cd n1
        sudo bash build.sh
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: docker-n1
        path: n1/opt/imgs
